-- MySQL Script generated by MySQL Workbench
-- sex 10 abr 2026 13:59:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_bancario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sistema_bancario` ;

-- -----------------------------------------------------
-- Schema sistema_bancario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_bancario` ;
USE `sistema_bancario` ;

-- -----------------------------------------------------
-- Table `sistema_bancario`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_bancario`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `sistema_bancario`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(14) NOT NULL,
  `senha` VARCHAR(64) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_bancario`.`ContaBancaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_bancario`.`ContaBancaria` ;

CREATE TABLE IF NOT EXISTS `sistema_bancario`.`ContaBancaria` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `agencia` VARCHAR(6) NOT NULL,
  `saldo` DECIMAL(10,2) NOT NULL,
  `fk_usuario_cpf` VARCHAR(14) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'ATIVA',
  PRIMARY KEY (`numero`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE,
  INDEX `fk_ContaBancaria_Usuario_idx` (`fk_usuario_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_ContaBancaria_Usuario`
    FOREIGN KEY (`fk_usuario_cpf`)
    REFERENCES `sistema_bancario`.`Usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1000;


-- -----------------------------------------------------
-- Table `sistema_bancario`.`Transacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_bancario`.`Transacao` ;

CREATE TABLE IF NOT EXISTS `sistema_bancario`.`Transacao` (
  `idTransacao` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `data` DATETIME NOT NULL,
  `contaDestino` INT NOT NULL,
  `fk_conta_origem` INT NOT NULL,
  PRIMARY KEY (`idTransacao`),
  UNIQUE INDEX `idTransacao_UNIQUE` (`idTransacao` ASC) VISIBLE,
  INDEX `fk_Transacao_ContaBancaria1_idx` (`fk_conta_origem` ASC) VISIBLE,
  CONSTRAINT `fk_Transacao_ContaBancaria1`
    FOREIGN KEY (`fk_conta_origem`)
    REFERENCES `sistema_bancario`.`ContaBancaria` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
